# Example config file for controller
mysql_instances:
  default:
    host: 127.0.0.1
    user: root
    password: mysql
    port: 3306
  instance2:
    host: 127.0.0.1
    user: root
    password: mysql
    port: 3306
