{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "mysql-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "mysql-controller.name" . }}
    helm.sh/chart: {{ include "mysql-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "mysql-controller.fullname" . }}
rules:
  - apiGroups: ["signifly.io"]
    resources: ["mysqldatabases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
{{- end -}}
