apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqldatabases.signifly.io
  labels:
    app: {{ template "mysql-controller.name" . }}
    chart: {{ template "mysql-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "mysql-controller.name" . }}
    helm.sh/chart: {{ include "mysql-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: signifly.io
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: DBNAME
          type: string
          description: The name of the database
          jsonPath: .spec.dbName
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - dbName
                - dbUserName
                - dbUserPassword
              properties:
                dbName:
                  type: string
                dbUserName:
                  type: string
                dbUserPassword:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                dbInstanceId:
                  type: string
                extraSQL:
                  type: string
                onDeletion:
                  type: object
                  properties:
                    dropDB:
                      type: boolean
                    dropUser:
                      type: boolean
  scope: Namespaced
  names:
    plural: mysqldatabases
    singular: mysqldatabase
    kind: MysqlDatabase
    shortNames:
    - mysqldb

