apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-controller.fullname" . }}
  labels:
    app: {{ template "mysql-controller.name" . }}
    chart: {{ template "mysql-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "mysql-controller.name" . }}
    helm.sh/chart: {{ include "mysql-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mysql-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "mysql-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ template "mysql-controller.name" . }}
        release: {{ .Release.Name }}
{{- if .Values.pod_labels }}
{{ toYaml .Values.pod_labels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "mysql-controller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CURRENT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            - name: CONFIG_FILE
              value: "/config/mysql-controller.yaml"
            - name: LOG_LEVEL
              value: "{{ .Values.log_level }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "mysql-controller.fullname" . }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
