# If dbInstanceId is not in the resource, the controller will look for a `default` key
apiVersion: signifly.io/v1
kind: MysqlDatabase
metadata:
  name: app1
spec:
  dbName: db1
  dbUserName: user1
  dbUserPassword:
    name: mySecret
    key: myKey
  # This string must correspond to a key in one of `mysql_instances` in the config file
  dbInstanceId: default
---
apiVersion: signifly.io/v1
kind: MysqlDatabase
metadata:
  name: app2
spec:
  dbName: db2
  dbUserName: user2
  dbUserPassword:
    name: mySecret
    key: myKey
  # This string must correspond to a key in one of `mysql_instances` in the config file
  dbInstanceId: instance2
