apiVersion: signifly.io/v1
kind: MysqlDatabase
metadata:
  name: app3
spec:
  dbName: db3
  dbUserName: user3
  dbUserPassword: swordfish
  onDeletion:
    # Whether to drop the databse when the resource is deleted
    dropDB: false
    # Whether to drop the role when the resource is deleted
    dropUser: false
